# Version of Docker compose file
version: "3.8"

services:
# Defining the service
  mongodb:
# Defining the base image to be used 
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
#    volumes:
#      - /mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
# Defining the environmental variable
    environment:
      # ENVIRONMET_VARIABLE_NAME: "environment variable value" 
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=grupo17
      - MONGO_INITDB_ROOT_PASSWORD=grupo17